<?php
    include("includes/add_image_size.php");
    include("includes/add_theme_support.php");
    include("includes/add_widgets.php");
    include("includes/reg_menus.php");
    include("includes/reg_post_types.php");
    include("includes/reg_taxonomies.php");
    include("includes/custom_fields.php");
 ?>
