<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_events',
		'title' => 'Events',
		'fields' => array (
			array (
				'key' => 'field_5a1c1f4b843b6',
				'label' => 'Title',
				'name' => 'title',
				'type' => 'text',
				'instructions' => 'Event title',
				'required' => 1,
				'default_value' => '',
				'placeholder' => 'Title',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => 40,
			),
			array (
				'key' => 'field_5a1c22f2f3dfb',
				'label' => 'Image',
				'name' => 'image',
				'type' => 'image',
				'instructions' => 'Image for display.',
				'save_format' => 'object',
				'preview_size' => 'single_large',
				'library' => 'all',
			),
			array (
				'key' => 'field_5a1c14a0a9ba0',
				'label' => 'Text',
				'name' => 'text',
				'type' => 'textarea',
				'instructions' => 'Describe the event and include all the information needed.',
				'required' => 1,
				'default_value' => '',
				'placeholder' => 'Description and information',
				'maxlength' => 2000,
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5a1c26570a072',
				'label' => 'Date & Time',
				'name' => 'date_&_time',
				'type' => 'date_time_picker',
				'instructions' => 'Select the date and time for the event.',
				'show_date' => 'true',
				'date_format' => 'm/d/y',
				'time_format' => 'h:mm tt',
				'show_week_number' => 'false',
				'picker' => 'slider',
				'save_as_timestamp' => 'true',
				'get_as_timestamp' => 'false',
			),
			array (
				'key' => 'field_5a1c157ba9ba2',
				'label' => 'Location',
				'name' => 'location',
				'type' => 'text',
				'instructions' => 'Add the location of the event.',
				'default_value' => '',
				'placeholder' => 'Location',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => 60,
			),
			array (
				'key' => 'field_5a1c21b7d0f0b',
				'label' => 'Excerpt',
				'name' => 'excerpt',
				'type' => 'textarea',
				'instructions' => 'Short introduction to your event that will be shown on the front page.',
				'required' => 1,
				'default_value' => '',
				'placeholder' => 'Short introduction',
				'maxlength' => 200,
				'rows' => '',
				'formatting' => 'br',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'event',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_members',
		'title' => 'Members',
		'fields' => array (
			array (
				'key' => 'field_5a1c293106979',
				'label' => 'Name',
				'name' => 'name',
				'type' => 'text',
				'instructions' => 'First and last name of the new member.',
				'required' => 1,
				'default_value' => '',
				'placeholder' => 'Name',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => 60,
			),
			array (
				'key' => 'field_5a1c29640697a',
				'label' => 'Image',
				'name' => 'image',
				'type' => 'image',
				'instructions' => 'Image of the new member.',
				'required' => 1,
				'save_format' => 'object',
				'preview_size' => 'large_grid_thumbnail',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'members',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_news',
		'title' => 'News',
		'fields' => array (
			array (
				'key' => 'field_5a1c277cc9f2a',
				'label' => 'Title',
				'name' => 'title',
				'type' => 'text',
				'instructions' => 'News title',
				'required' => 1,
				'default_value' => '',
				'placeholder' => 'Title',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => 40,
			),
			array (
				'key' => 'field_5a1d1e64d6300',
				'label' => 'Image',
				'name' => 'image',
				'type' => 'image',
				'instructions' => 'Image for display.',
				'save_format' => 'object',
				'preview_size' => 'single_large',
				'library' => 'all',
			),
			array (
				'key' => 'field_5a1c27af36bb9',
				'label' => 'Text',
				'name' => 'text',
				'type' => 'textarea',
				'instructions' => 'Write your news article and include all the information needed.',
				'default_value' => '',
				'placeholder' => 'News article and information',
				'maxlength' => 2000,
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5a1c2812b99e0',
				'label' => 'Excerpt',
				'name' => 'excerpt',
				'type' => 'textarea',
				'instructions' => 'Short introduction to your news article that will be shown on the front page.',
				'required' => 1,
				'default_value' => '',
				'placeholder' => 'Short introduction',
				'maxlength' => 200,
				'rows' => '',
				'formatting' => 'br',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'news',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	
	// pages
	register_field_group(array (
		'id' => 'acf_contact-page',
		'title' => 'Contact Page',
		'fields' => array (
			array (
				'key' => 'field_5a1dc203be5ab',
				'label' => 'Text',
				'name' => 'text',
				'type' => 'text',
				'instructions' => 'Text to be displayed on the page.',
				'default_value' => '',
				'placeholder' => 'Text',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5a1dc246be5ac',
				'label' => 'Image',
				'name' => 'image',
				'type' => 'image',
				'instructions' => 'Image to be displayed on the page.',
				'save_format' => 'object',
				'preview_size' => 'large_grid_thumbnail',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '10',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				//7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_event-page',
		'title' => 'Event Page',
		'fields' => array (
		),
		'location' => array (
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '6',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				//7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_members-page',
		'title' => 'Members Page',
		'fields' => array (
		),
		'location' => array (
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '14',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				//7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_news-page',
		'title' => 'News Page',
		'fields' => array (
		),
		'location' => array (
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '4',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				//7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_organization-page',
		'title' => 'Organization Page',
		'fields' => array (
			array (
				'key' => 'field_5a1dc2b5a43d5',
				'label' => 'Text',
				'name' => 'text',
				'type' => 'text',
				'instructions' => 'Text to be displayed on the page.',
				'default_value' => '',
				'placeholder' => 'Text',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5a1dc2c9a43d6',
				'label' => 'Image',
				'name' => 'image',
				'type' => 'image',
				'instructions' => 'Image to be displayed.',
				'save_format' => 'object',
				'preview_size' => 'single_large',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '12',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				//7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_template-page',
		'title' => 'Template Page',
		'fields' => array (
			array (
				'key' => 'field_5a1dc8d253df9',
				'label' => 'Text',
				'name' => 'text',
				'type' => 'text',
				'instructions' => 'Text to be displayed on the page.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5a1dc8f653dfa',
				'label' => 'Image',
				'name' => 'image',
				'type' => 'image',
				'instructions' => 'Image to be displayed',
				'save_format' => 'object',
				'preview_size' => 'single_large',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'default',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				//7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
}

?>
